# Generated by Django 2.2.6 on 2019-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_addben'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.BigIntegerField(default=500000),
        ),
    ]
