# Generated by Django 2.2.6 on 2019-10-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20191028_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account',
            field=models.CharField(default='', max_length=12),
        ),
    ]
